name: Deploy React to AWS Elastic Beanstalk
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    # defaults:
      # run:
      #   working-directory: ./frontend-app
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          cd frontend-app
          npm install

      - name: Build Project
        run: |
          cd frontend-app
          npm run build

      - name: Create ZIP Archive
        run: |
          cd frontend-app
          zip -r ../frontend_app_deployment.zip
      
      - name: Deploy to Elastic Beanstalk please
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: example-react-app
          environment_name: Example-react-app-env
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-us-east-1-116981765536
          region: us-east-1
          deployment_package: frontend_app_deployment.zip
        